import { Card } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { FileText, Download } from 'lucide-react';
import { formatCurrency } from '../../lib/utils';

interface Contract {
  id: string;
  project: string;
  freelancer: string;
  client: string;
  type: string;
  signedDate: string;
  status: string;
  budget: number;
  timeline: string;
}

function generateContractText(contract: Contract): string {
  return `
MIRAICRAFT STANDARD CONTRACT AGREEMENT
=======================================

Project Title   : ${contract.project}
Client Name     : ${contract.client}
Instructor/Freelancer : ${contract.freelancer}
Contract Type   : ${contract.type}
Budget          : ${formatCurrency(contract.budget)}
Timeline        : ${contract.timeline}
Signed Date     : ${contract.signedDate}
Status          : ${contract.status}

---------------------------------------
TERMS & CONDITIONS
---------------------------------------

1. NON-DISCLOSURE AGREEMENT (NDA)
The Freelancer agrees to keep all project information strictly confidential and
shall not disclose any proprietary information to third parties without prior
written consent from the Client. This obligation survives termination.

2. WORK-FOR-HIRE
All work product created by the Freelancer shall be considered "work made for
hire." The Client shall own all rights, title, and interest — including
intellectual property rights — in all deliverables upon full payment.

3. PAYMENT TERMS
Payment of ${formatCurrency(contract.budget)} shall be released in milestones as agreed upon in
the project details. Each milestone is reviewed and approved by the Client
within 7 days of submission.

4. PLATFORM FEE
MiraiCraft retains a platform fee of 20% of all project payments. The
Freelancer's net earnings are ${formatCurrency(Math.floor(contract.budget * 0.8))}.

5. TERM AND TERMINATION
Either party may terminate this agreement with 7 days written notice. Upon
termination, the Freelancer shall be compensated for all completed milestones.

6. DISPUTE RESOLUTION
Any disputes shall be resolved first through MiraiCraft's mediation service,
and if unresolved, through binding arbitration.

7. GOVERNING LAW
This agreement is governed by the laws of India.

---------------------------------------
SIGNATURES
---------------------------------------

By accepting this project on MiraiCraft, both parties agree to be bound by
these terms and conditions.

Client Signature  : ${contract.client}       Date: ${contract.signedDate}
Freelancer Signature : ${contract.freelancer}    Date: ${contract.signedDate}

---------------------------------------
Generated by MiraiCraft Platform — ${new Date().toLocaleDateString('en-IN')}
`.trim();
}

function downloadContract(contract: Contract) {
  const text = generateContractText(contract);
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `MiraiCraft_Contract_${contract.project.replace(/\s+/g, '_')}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function ClientContracts() {
  const contracts: Contract[] = [
    {
      id: '1',
      project: 'E-commerce Website Redesign',
      freelancer: 'John Doe',
      client: 'Acme Corp',
      type: 'NDA + Work-for-hire',
      signedDate: 'April 16, 2026',
      status: 'Active',
      budget: 200000,
      timeline: '4-6 weeks',
    },
    {
      id: '2',
      project: 'Mobile App Dashboard',
      freelancer: 'Jane Smith',
      client: 'TechStart Inc',
      type: 'NDA + Work-for-hire',
      signedDate: 'April 11, 2026',
      status: 'Active',
      budget: 160000,
      timeline: '3-4 weeks',
    },
    {
      id: '3',
      project: 'SEO Optimization',
      freelancer: 'Mike Johnson',
      client: 'BrandBoost Ltd',
      type: 'NDA + Work-for-hire',
      signedDate: 'March 21, 2026',
      status: 'Completed',
      budget: 80000,
      timeline: '2-3 weeks',
    },
  ];

  return (
    <div>
      <h1 className="text-3xl mb-8">Contracts & Documents</h1>

      <Card className="overflow-hidden mb-8">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="text-left py-3 px-6">Project</th>
                <th className="text-left py-3 px-6">Freelancer</th>
                <th className="text-left py-3 px-6">Contract Type</th>
                <th className="text-left py-3 px-6">Signed Date</th>
                <th className="text-left py-3 px-6">Status</th>
                <th className="text-left py-3 px-6">Actions</th>
              </tr>
            </thead>
            <tbody>
              {contracts.map((contract) => (
                <tr key={contract.id} className="border-t">
                  <td className="py-4 px-6">{contract.project}</td>
                  <td className="py-4 px-6">{contract.freelancer}</td>
                  <td className="py-4 px-6">{contract.type}</td>
                  <td className="py-4 px-6 text-sm text-gray-600">{contract.signedDate}</td>
                  <td className="py-4 px-6">
                    <span
                      className={`px-2 py-1 text-sm rounded ${
                        contract.status === 'Active'
                          ? 'bg-green-100 text-green-800'
                          : 'bg-gray-100 text-gray-800'
                      }`}
                    >
                      {contract.status}
                    </span>
                  </td>
                  <td className="py-4 px-6">
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm">
                        <FileText className="w-4 h-4 mr-1" />
                        View
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => downloadContract(contract)}
                        title="Download contract"
                      >
                        <Download className="w-4 h-4" />
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <Card className="p-6">
        <h2 className="text-xl mb-4">Contract Template Preview</h2>
        <div className="bg-gray-50 rounded-lg p-6 max-h-96 overflow-y-auto">
          <h3 className="mb-4">MiraiCraft Standard Agreement</h3>
          <div className="space-y-4 text-sm text-gray-700">
            <p>
              This agreement is entered into between the Client and the Freelancer for the project
              posted on MiraiCraft platform.
            </p>
            <h4>1. Non-Disclosure Agreement (NDA)</h4>
            <p>
              The Freelancer agrees to keep all project information confidential and not to disclose
              any proprietary information to third parties.
            </p>
            <h4>2. Work-for-Hire</h4>
            <p>
              All work product created by the Freelancer shall be considered "work made for hire"
              and the Client shall own all rights, title, and interest in the work product.
            </p>
            <h4>3. Payment Terms</h4>
            <p>
              Payment shall be made according to the milestones agreed upon in the project details.
              Each milestone payment is released upon client approval.
            </p>
            <h4>4. Term and Termination</h4>
            <p>
              Either party may terminate this agreement with 7 days written notice. Upon termination,
              the Freelancer shall be paid for all completed work.
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}


